# CNN

## Fully-connected Layer (퍼셉트론)

- FC Layer는 1차원 데이터를 요구
- 이미지를 단순하게 1차원으로 바꾸면 2차원 상에서 가지는 정보를 포기해야함
  - 이미지 내 사물 간의 거리 관계 등
  - 색의 변화 -세로로 변하는 상황
- 즉 공간정보(Spatial Information)가 무너짐

## Convolutional Neural Network

- 따라서 이미지 처리에 특화된 딥러닝 모델이 등장

- CNN의 대표적인 구성 요소
  - Convolutional Layer
  - Pooling Layer
  - 분류기(Classifier): Fully-connected layer로 구성

- Convolution 연산
  - CNN을 구현하는 핵심 연산
  - 커널과 Convolution 연산
    - 전통적인 이미지 처리 분야에서 커널(필터)이란 것이 존재
    - 이미지의 커널 간의 Convolution 연산으로 처리
  - 2차원 이미지 데이터: 행렬로 표현 가능
    - 행렬의 각 원소는 해당 위치의 이미지 픽셀값
  - Convolution 커널 : 행렬로 표현 가능
  - Convolution 연산은 2차원 상에서 연산이 이루어지므로 이미지 데이터를 변형 없이 그대로 사용 가능

## Convolution 연산 과정

- 이미지 * 커널 = 결과

### Convolution 연산 용어

- 연산 결과 : Feature Map 또는 Activation Map이라 부름
- 커널과 이미지가 겹치는 영역 : 수용 영역(Receptive Field)

- 컬러 이미지의 Convolution 연산
  - 앞선 예시는 이미지의 채널이 1개 = 흑백 이미지
  - 컬러 이미지는 채널이 3개
  - 이 경우 커널도 채널을 3개로 준비
  - 각 채널별로 Convolution 연산을 수행하고 각 결과를 더해서 하나의 Feature Map을 생성
  - 커널을 여러 개 두면 Feature Map도 여러개 생성

## Convolutional Neural Network

- 지금까지 사용한 커널들은 학습 가능한 커널
  - 즉 커널 행렬의 각 값들이 가중치
- 이러한 커널들로 이루어진 Layer를 Convolutional Layer라고 부름
  - 이 Layer들을 쌓아서 CNN을 구성

### Layer 역활

- 이미지가 가지는 특징 Feature를 뽑아내도록 커널을 학습
- 커널에 따라 추출하는 Feature를 다르게 학습
- 이미지 내의 대각선, 원형, 색조 등등이 이러한 Feature에 해당

### Stride

- Convolution 연산 과정을 조절하기 위한 Hyperparameter
- 커널 이미지 내에서 이동하는 칸수를 조절

### Padding

- Padding을 추가하여 Feature Map사이즈가 줄어드는 현상 방지
- 또한 이미지의 테두리 정보도 균일하게 활용

### Convolutional Layer 의의

- 왜 이미지 특징을 잘 뽑아내는가?
  - Convolution 연산은 하나의 커널이 픽셀간의 정보를 보게 만듦
  - 하나의 커널이 이미지 전체 영역을 보고 학습

- Parameter Sharing
  - 커널이 가진 Parameter를 이미지의 모든 영역에서 공유
  - Parameter 개수를 FC Layer에 비해 극적으로 줄임
    - 과적합 방지

### Convolutional Layer 활성화 함수

- Convolution 연산 또한 선형 연산
  - 모두 곱셈과 덧셈으로만 이루어짐

- 따라서 FC Layer처럼 비선형성을 추가하기 위해 활성화 함수를 사용
  - CNN은 주로 ReLU함수 사용

## Pooling Layer

- CNN에서 거의 항상 같이 쓰이는 Layer
  - 주 역활 : Feature Map의 사이즈를 줄여서 Parameter 개수를 줄이는 것

- Max Pooling
  - 주어진 이미지나 Feature Map을 더 작은 영역으로 분할
  - 위 그림은 각 영역의 크기가 2*2 가 되도록 분할
  - 각 영역에서 최대값을 뽑아내어 새로운 Feature Map을 구성

- 일반적으로 Max Pooling을 많이 사용
  - Feature Map에 존재하는 Feature중 가장 영향력이 큰 Feaure만 사용
- Feature Map의 채널이 여러 개면 채널별로 Pooling 연산 수행
- 추가 Pooling Layer
  - Global Average Pooling 전체 Feature Map에서 하나의 평균값을 계산
  - Global Max Pooling 전체 Feature Map에서 하나의 최대값을 계산
  - 둘 다 마찬가지로 채널 별로 연산

## 분류기 Classifier

- CNN은 일반적으로 이미지 분류 목적으로 사용
- Feature Map을 Fully-connected Layer에 통과시켜 분류를 수행
- 이를 위해 Feature Map을 1차원으로 변형

## 대표적인 CNN 모델

### LeNet (1990)

- 우편번호 인식

### AlexNet (2012)

- ImageNet Challenge 우승
  - ReLU 활성화 함수 소개
  - 딥러닝 모델 학습에 GPU를 활용 -> 이후로 사실상 모든 딥러닝 모델은 GPU로 학습

### VGGNet (2014)

- 커널 사이즈를 모두 3*3으로 통일
- Parameter수 증가를 억제하면서 모델 층을 더 많이 쌓을 수 있게 됨
- 층이 많을수록 일반적으로 성능이 향상됨

### ResNet (2015)

- Layer 개수를 최대 152개까지 늘림
- 깊은 모델에서 필연적으로 나타나는 현상
  - Vanishing Gradient

- 기울기 소실 Vanishing Gradient
  - 역전파 과정에서 기울기 값이 점점 작아지다 0에 수렴하면서 발생

- Residual Connection
  - 기울기 소실문제를 해결하기 위한 구조
  - 이를 통해 Layer 개수를 극적으로 늘림
  - 기존 Convolutional Layer들을 우회하는 연결

- 분류 작업이 아닌 경우에 사용하는 모델은
  - 일반적으로 분류 모델과 유사하게 CNN을 구성
  - 모델의 출력값, 손실 함수, 데이터셋 구성 등이 완전히 다르게 이루어짐
    - YOLO, R-CNN, U-Net

## Tensorflow로 conv2d 사용하기

In [1]:
import tensorflow as tf
from tensorflow import keras

In [2]:
inp = tf.ones((1, 3, 3, 1)) # 3x3 x1 이미지가 1개 (1,높이,너비,1)
print(inp)

# [[[[1][1][1]]
#   [[1][1][1]]
#   [[1][1][1]]]]

tf.Tensor(
[[[[1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]]]], shape=(1, 3, 3, 1), dtype=float32)


In [3]:
filter = tf.ones((2, 2, 1, 1)) # 2x2 x1 짜리 필터가 1개 
print(filter)

# [ [ [[1.]],[[1.]] ],
#   [ [[1.]],[[1.]] ] ] 

tf.Tensor(
[[[[1.]]

  [[1.]]]


 [[[1.]]

  [[1.]]]], shape=(2, 2, 1, 1), dtype=float32)


In [4]:
strides = [1, 1] # [높이, 너비]

In [6]:
output = tf.nn.conv2d(inp, filter, strides ,padding = 'VALID') # padding을 'VALID'으로 설정 = 패딩을 하지 않음
print(output)
# [[  [[4.] [4.]]
#     [[4.] [4.]]  ]], shape=(1, 2, 2, 1), dtype=float32)

tf.Tensor(
[[[[4.]
   [4.]]

  [[4.]
   [4.]]]], shape=(1, 2, 2, 1), dtype=float32)


In [7]:
output = tf.nn.conv2d(output, filter, strides, padding = 'VALID') # 한번 더 적용
print(output)

tf.Tensor([[[[16.]]]], shape=(1, 1, 1, 1), dtype=float32)


## Tensorflow.Keras로 Conv2D 사용하기