# 복습

## 숙제

In [16]:
def add_all(*inputs):
  s=0
  for i in range(len(inputs[0])):
    s +=inputs[0][i]
  return s

In [17]:
add_all([1,2,3,4,5,6,7,8,9,10])

55

In [18]:
sentence = "Life is too short, you need python!"
deleted = [c for c in sentence if c not in 'aeiou']
''.join(deleted)

'Lf s t shrt, y nd pythn!'

# Numpy
## numpy 연산

In [3]:
import numpy as np

A = np.array([1,2,3,4])
print(type(A))
A = np.array([[1,2],[3,4]])
print(A)
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr+arr)
print(arr/arr)
print(arr*arr)
print(arr-arr)

<class 'numpy.ndarray'>
[[1 2]
 [3 4]]
[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[ 1  4  9]
 [16 25 36]]
[[0 0 0]
 [0 0 0]]


### 브로드캐스팅

In [4]:
print(arr-1)
print(arr+1)
print(1+arr)
arr2 = np.array([1,2,3])
print(arr+arr2)

[[0 1 2]
 [3 4 5]]
[[2 3 4]
 [5 6 7]]
[[2 3 4]
 [5 6 7]]
[[2 4 6]
 [5 7 9]]


In [5]:
arr3 = np.array([1,2])
print(arr+arr3)
# 에러

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [ ]:
arr4 = np.array([[1],[2]])
print(arr+arr4)

[[2 3 4]
 [6 7 8]]


In [6]:
arr = np.arange(12).reshape((3, 4))
arr2 = np.arange(8).reshape((2, 4))

In [7]:
print(arr)
print(arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1 2 3]
 [4 5 6 7]]


In [8]:
arr + arr2
# 에러

ValueError: operands could not be broadcast together with shapes (3,4) (2,4) 

In [9]:
arr = np.arange(8).reshape((4, 2))
arr2 = np.arange(4).reshape((2, 2))
print(arr)
print()
print(arr2)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]

[[0 1]
 [2 3]]


In [10]:
arr + arr2
# 에러

ValueError: operands could not be broadcast together with shapes (4,2) (2,2) 

In [11]:
A = np.array(10)
print(A.ndim)
B = np.array([1, 2])
print(B.ndim)
C = np.array([[1, 2]])
print(C.ndim)
D = np.array([[[1, 2]]])
print(D.ndim)

0
1
2
3


In [12]:
print(A.shape)
print(B.shape)
print(C.shape)
print(D.shape)

()
(2,)
(1, 2)
(1, 1, 2)


In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
print(np.zeros((3, 3)), "\n")
print(np.ones((3, 3)), "\n")
print(np.identity(3), "\n")
print(np.eye(3, 5, dtype=int), "\n")

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]] 



In [15]:
# linspace(start,stop,nuim,endpoint,retstep)

np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [16]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [17]:
a = np.array([1,2,3])
b = np.array([4,5,6])
arr = np.hstack([a, b])
print(arr)

[1 2 3 4 5 6]


In [18]:
a = np.array([1,2,3])
b = np.array([4,5,6])
arr = np.vstack([a, b])
print(arr)

[[1 2 3]
 [4 5 6]]


In [19]:
a = np.array([1,2,3])
b = np.array([4,5,6])
arr = np.concatenate([a, b], axis=0)
print(arr)
# arr = np.concatenate([a, b], axis=1)
# print(arr)
# 1줄짜리 arr는 세로로 합치기 불가

[1 2 3 4 5 6]


In [20]:
a = np.array([[1,2,3]])
b = np.array([[4,5,6]])
arr = np.concatenate([a, b], axis=0)
print(arr)
arr = np.concatenate([a, b], axis=1)
print(arr)

[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]


In [29]:
a = np.array([[[1,2,3]]])
b = np.array([[[4,5,6]]])
arr = np.concatenate([a, b], axis=0)
print(arr)
arr = np.concatenate([a, b], axis=1)
print(arr)
arr = np.concatenate([a, b], axis=2)
print(arr)

[[[1 2 3]]

 [[4 5 6]]]
[[[1 2 3]
  [4 5 6]]]
[[[1 2 3 4 5 6]]]


In [40]:
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[7,8,9],[10,11,12]])

np.concatenate((c,d),axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [41]:
np.column_stack([c,d])

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [42]:
#random
import random

random.random() # 0<=리턴값<=1

0.00669670338867101

In [43]:
random()

TypeError: 'module' object is not callable

In [44]:
import random
data = [1,2,3,4,5,6,7]

random.choice(data)#choice : 매개변수로 시퀀스 타입(문자열,튜플,리스트)을 받음. 그 중에서 무작위로 하나로 선택하여 리턴

7

In [45]:
import numpy 

def make_lotto(count):
  for i in range(count):
    lotto_num =[] #로또 번호가 담길 리스트형 변수
    for j in range(6): #6번 반복
      lotto_num = numpy.random.choice(range(1,46),6,replace = False) #nCr :n개 중에 r를 순서와 상관없이 뽑아주세요. range(1,46),6->6개를 뽑아주세요
      #replace ->복원 추출을 막아주세요.
      lotto_num.sort()
    print('{}.로또 번호 : {}'.format(i+1, lotto_num))


In [47]:
count = int(input('로또 번호를 몇 개 생성할까요?'))
make_lotto(count)

1.로또 번호 : [ 2  5 11 33 34 39]
2.로또 번호 : [ 3 20 28 34 39 41]


In [48]:
arr = np.zeros((3,2))
arr.flatten() # revel() VS flatten () ->flatten 을 많이 씀.

array([0., 0., 0., 0., 0., 0.])

In [49]:
arr3 = arr.reshape(-1,2)
arr3

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [50]:
arr4 = arr.reshape(-1,-1)

ValueError: can only specify one unknown dimension

In [51]:
arr.transpose()

array([[0., 0., 0.],
       [0., 0., 0.]])

In [52]:
arr.T

array([[0., 0., 0.],
       [0., 0., 0.]])

In [53]:
import numpy as np

arr = np.arange(0,21)
arr1 = []
arr2 = []
for i in arr:
  if arr[i] %2==0:
    arr1.append(arr[i])
  else:
    arr2.append(arr[i])

In [54]:
import numpy as np
arr = np.arange(0,21)


arr1 = arr[arr%2==0]
arr2 = arr[arr%2!=0]

In [55]:
lst = list(range(6))
lst

[0, 1, 2, 3, 4, 5]

In [56]:
arr1d = np.arange(6)
arr1d

array([0, 1, 2, 3, 4, 5])

In [57]:
a = np.random.randint(-3,3,10).reshape(2,5)
b = np.random.randint(0,5,15).reshape(5,3)
b = b.T

print(a.shape,b.shape)

(2, 5) (3, 5)


In [58]:
frame = pd.DataFrame(np.arange(24).reshape(4,-1),
                     columns = ['c1','c2','c3','c4','c5','c6'],
                     index = ['r1','r2','r3','r4'])

frame

c1  c2  c3  c4  c5  c6
r1   0   1   2   3   4   5
r2   6   7   8   9  10  11
r3  12  13  14  15  16  17
r4  18  19  20  21  22  23

In [59]:
frame['c3']

r1     2
r2     8
r3    14
r4    20
Name: c3, dtype: int32

In [60]:
frame.c3

r1     2
r2     8
r3    14
r4    20
Name: c3, dtype: int32

In [61]:
frame[['c1','c2']]

c1  c2
r1   0   1
r2   6   7
r3  12  13
r4  18  19

In [62]:
frame['r1':'r2']

c1  c2  c3  c4  c5  c6
r1   0   1   2   3   4   5
r2   6   7   8   9  10  11

In [63]:
frame['c1':'c2']

Empty DataFrame
Columns: [c1, c2, c3, c4, c5, c6]
Index: []

In [64]:

frame.iloc[[0],[3]]

c4
r1   3

In [65]:
frame.iloc[[0,1],1:4]

c2  c3  c4
r1   1   2   3
r2   7   8   9

In [66]:

frame.loc[['r1'],['c4']]

c4
r1   3

In [67]:
frame.loc['r1':'r2',['c2','c3','c4']]

c2  c3  c4
r1   1   2   3
r2   7   8   9

In [38]:
import pandas as pd

df = pd.read_csv('./data/stock_2020_01.csv', encoding='cp949')
df.head(2)

Date    kospi  kosdaq  gold_fut_132030  Bond_273130
0  2020. 1. 2 오후 3:30:00  2175.17  674.02            10845       108215
1  2020. 1. 3 오후 3:30:00  2176.46  669.93            11000       108565

In [39]:
df.describe()

kospi      kosdaq  gold_fut_132030  Bond_273130
count    20.00000   20.000000        20.000000      20.0000
mean   2203.44250  671.117000     11112.000000  108188.7500
std      43.83648   14.040831       115.762916     364.6912
min    2119.01000  640.940000     10845.000000  107695.0000
25%    2175.44750  664.385000     11053.750000  107942.5000
50%    2196.42000  673.525000     11080.000000  108030.0000
75%    2241.30000  680.282500     11187.500000  108478.7500
max    2267.25000  688.410000     11360.000000  108810.0000

In [68]:
df.isna().sum()
df.isnull().sum()

Date               0
kospi              0
kosdaq             0
gold_fut_132030    0
Bond_273130        0
dtype: int64

In [70]:
df = pd.read_csv('./data/kbo.csv')

In [72]:
df.describe()

연도         순위    경기수          승          패          무  \
count    30.000000  30.000000   30.0  30.000000  30.000000  30.000000   
mean   2018.000000   5.466667  144.0  71.200000  71.200000   1.600000   
std       0.830455   2.921187    0.0  11.871147  11.591912   1.275769   
min    2017.000000   1.000000  144.0  48.000000  51.000000   0.000000   
25%    2017.000000   3.000000  144.0  61.250000  62.500000   1.000000   
50%    2018.000000   5.000000  144.0  70.500000  71.500000   1.000000   
75%    2019.000000   8.000000  144.0  79.000000  80.750000   2.000000   
max    2019.000000  10.000000  144.0  93.000000  94.000000   5.000000   

              승률        게임차  
count  30.000000  30.000000  
mean    0.499800  12.833333  
std     0.082079  12.576204  
min     0.340000 -14.500000  
25%     0.431750   2.375000  
50%     0.494500   9.750000  
75%     0.558000  19.500000  
max     0.646000  39.000000

In [74]:
df.shape

(30, 9)

In [76]:
df.isna().sum()

연도     0
순위     0
팀      0
경기수    0
승      0
패      0
무      0
승률     0
게임차    0
dtype: int64

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   연도      30 non-null     int64  
 1   순위      30 non-null     int64  
 2   팀       30 non-null     object 
 3   경기수     30 non-null     int64  
 4   승       30 non-null     int64  
 5   패       30 non-null     int64  
 6   무       30 non-null     int64  
 7   승률      30 non-null     float64
 8   게임차     30 non-null     float64
dtypes: float64(2), int64(6), object(1)
memory usage: 2.2+ KB


In [78]:
df["팀"].unique()

array(['두산', '키움', 'SK', 'LG', 'NC', 'KT', 'KIA', '삼성', '한화', '롯데', '넥센'],
      dtype=object)

In [80]:
df.groupby('팀').count()

연도  순위  경기수  승  패  무  승률  게임차
팀                                 
KIA   3   3    3  3  3  3   3    3
KT    3   3    3  3  3  3   3    3
LG    3   3    3  3  3  3   3    3
NC    3   3    3  3  3  3   3    3
SK    3   3    3  3  3  3   3    3
넥센    2   2    2  2  2  2   2    2
두산    3   3    3  3  3  3   3    3
롯데    3   3    3  3  3  3   3    3
삼성    3   3    3  3  3  3   3    3
키움    1   1    1  1  1  1   1    1
한화    3   3    3  3  3  3   3    3

In [83]:
df.groupby(['연도','팀']).sum()

순위  경기수   승   패  무     승률   게임차
연도   팀                                   
2017 KIA   1  144  87  56  1  0.608   0.0
     KT   10  144  50  94  0  0.347  37.5
     LG    6  144  69  72  3  0.489  17.0
     NC    4  144  79  62  3  0.560   7.0
     SK    5  144  75  68  1  0.524  12.0
     넥센    7  144  69  73  2  0.486  17.5
     두산    2  144  84  57  3  0.596   2.0
     롯데    3  144  80  62  2  0.563   6.5
     삼성    9  144  55  84  5  0.396  30.0
     한화    8  144  61  81  2  0.430  25.5
2018 KIA   5  144  70  74  0  0.486   8.5
     KT    9  144  59  82  3  0.418  18.0
     LG    8  144  68  75  1  0.476  10.0
     NC   10  144  58  85  1  0.406  20.0
     SK    2  144  78  65  1  0.545   0.0
     넥센    4  144  75  69  0  0.521   3.5
     두산    1  144  93  51  0  0.646 -14.5
     롯데    7  144  68  74  2  0.479   9.5
     삼성    5  144  68  72  4  0.486   8.5
     한화    3  144  77  67  0  0.535   1.5
2019 KIA   7  144  62  80  2  0.437  25.5
     KT    6  144  71  71  2  0.500  16.5
     LG    4  144  79  64  1  0.552   9.0
     NC    5  144  73  69  2  0.514  14.5
     SK    3  144  88  55  1  0.615   0.0
     두산    1  144  88  55  1  0.615   0.0
     롯데   10  144  48  93  3  0.340  39.0
     삼성    8  144  60  83  1  0.420  28.0
     키움    2  144  86  57  1  0.601   2.0
     한화    9  144  58  86  0  0.403  30.5

In [85]:
df.groupby(['연도','팀'])['승률','순위'].max()

<ipython-input-85-91cf4c5a4efa>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df.groupby(['연도','팀'])['승률','순위'].max()


승률  순위
연도   팀             
2017 KIA  0.608   1
     KT   0.347  10
     LG   0.489   6
     NC   0.560   4
     SK   0.524   5
     넥센   0.486   7
     두산   0.596   2
     롯데   0.563   3
     삼성   0.396   9
     한화   0.430   8
2018 KIA  0.486   5
     KT   0.418   9
     LG   0.476   8
     NC   0.406  10
     SK   0.545   2
     넥센   0.521   4
     두산   0.646   1
     롯데   0.479   7
     삼성   0.486   5
     한화   0.535   3
2019 KIA  0.437   7
     KT   0.500   6
     LG   0.552   4
     NC   0.514   5
     SK   0.615   3
     두산   0.615   1
     롯데   0.340  10
     삼성   0.420   8
     키움   0.601   2
     한화   0.403   9

In [1]:
df

NameError: name 'df' is not defined

In [ ]:
import matplotlib.pyplot import plt

plt.